"""Creating Tables

Revision ID: 2d5e0e76aa42
Revises: 
Create Date: 2023-04-05 16:48:22.544942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d5e0e76aa42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audio_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whisper_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('audio_input_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audio_input_id'], ['audio_inputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cgpt_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('whisper_output_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['whisper_output_id'], ['whisper_outputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cgpt_outputs')
    op.drop_table('whisper_outputs')
    op.drop_table('audio_inputs')
    op.drop_table('users')
    # ### end Alembic commands ###
